---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
#    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
#    volumes:
#     - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: true
#    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
